'use strict';
(() => {
const DATA=window.RECALL_BANK,KEY='probation-active-recall-all-v2',LEGACY='probation-active-recall-pilot-v1';
const $=id=>document.getElementById(id),clone=v=>JSON.parse(JSON.stringify(v));
const qs=new Map([...DATA.questions,...DATA.basic].map(q=>[q.id,q]));
const names={independent:'自行回想完成',prompted:'提示後完成',review:'需要再練',verify:'內容待核對'};
const emptyRound=()=>({draft:'',attempts:[],hint:false,phase:'writing',rating:null,done:false,note:'',verifyNote:''});
const newStore=()=>({version:2,active:null,sessions:{},legacyMigrated:false,filters:{subject:'心理學',year:'all',mode:'guided',search:'',reference:'all'}});
let state=newStore(),storageAvailable=true;
const keyFor=(id,mode)=>id+'::'+mode;
function getItems(q,mode){return mode==='original'?q.originalRounds:q.rounds;}
function validRound(r){return r&&typeof r.draft==='string'&&r.draft.length<=4000&&Array.isArray(r.attempts)&&r.attempts.length<1000&&r.attempts.every(a=>typeof a.text==='string'&&a.text.length<=4000&&typeof a.hint==='boolean')&&typeof r.hint==='boolean'&&['writing','submitted','checking'].includes(r.phase)&&[null,'independent','prompted','review','verify'].includes(r.rating)&&typeof r.done==='boolean'&&!(r.rating==='independent'&&(r.hint||r.attempts.length>1))&&(!r.done||!!r.rating)&&(!r.note||(typeof r.note==='string'&&r.note.length<=1000))&&(!r.verifyNote||(typeof r.verifyNote==='string'&&r.verifyNote.length<=1000));}
function validSession(s,key){const q=qs.get(s?.questionId);return q&&key===keyFor(q.id,s.mode)&&['guided','original','basic'].includes(s.mode)&&(s.mode!=='original'||q.originalRounds)&&(s.mode!=='basic'||q.year===null)&&(s.mode!=='guided'||q.year!==null)&&Array.isArray(s.rounds)&&s.rounds.length===getItems(q,s.mode).length&&s.rounds.every(validRound)&&Number.isInteger(s.index)&&s.index>=0&&s.index<=s.rounds.length&&typeof s.paused==='boolean'&&Array.isArray(s.history)&&(!isRequirements(q)||s.rounds.every(r=>r.rating!=='independent'));}
function validStore(s){return s?.version===2&&s.sessions&&typeof s.sessions==='object'&&!Array.isArray(s.sessions)&&Object.entries(s.sessions).every(([key,v])=>validSession(v,key))&&(!s.active||Object.hasOwn(s.sessions,s.active));}
function notice(text){$('notice').textContent=text;$('notice').hidden=false;}
function load(){try{const raw=localStorage.getItem(KEY);if(raw){const candidate=JSON.parse(raw);if(!validStore(candidate))throw Error('invalid');state=candidate;state.filters={...newStore().filters,...state.filters};}}catch{storageAvailable=false;notice('瀏覽器紀錄無法讀取或格式不相容。本次不覆寫原紀錄，仍可練習與匯出。');}if(!state.legacyMigrated&&storageAvailable){try{const old=JSON.parse(localStorage.getItem(LEGACY)||'null');if(old?.version===1&&old.rounds?.length===4&&old.rounds.every(validRound)){const k=keyFor('114-心理學-1','guided');if(!state.sessions[k]){state.sessions[k]={questionId:'114-心理學-1',mode:'guided',index:old.index,paused:old.paused,rounds:old.rounds.map(r=>({...emptyRound(),...r})),history:old.history||[],updatedAt:old.updatedAt||old.createdAt};if(!validSession(state.sessions[k],k)){delete state.sessions[k];}else{state.active=k;notice('已接續原本的信度與效度試作紀錄；舊版資料仍保留。');}}}state.legacyMigrated=true;}catch{notice('舊版試作紀錄未能轉入，原資料仍保留。');}}}
function persist(){state.updatedAt=new Date().toISOString();if(storageAvailable)try{localStorage.setItem(KEY,JSON.stringify(state));}catch{storageAvailable=false;notice('瀏覽器未能保存進度，請匯出全部紀錄備份。');}$('save-status').textContent=storageAvailable?'已保存在目前瀏覽器。':'目前僅保留在頁面，請匯出備份。';}
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text)n.textContent=text;if(cls)n.className=cls;return n;};
const active=()=>state.sessions[state.active];
const currentQuestion=()=>qs.get(active()?.questionId);
const isRequirements=q=>q.reference.kind==='requirements';
function updateSubjects(){const host=$('subjects');host.replaceChildren();DATA.subjects.forEach(({name,count})=>{const b=node('button',`${name} · ${count}`,'secondary');b.type='button';b.setAttribute('aria-pressed',String(state.filters.subject===name));b.onclick=()=>{state.filters.subject=name;state.filters.year='all';state.filters.search='';$('search').value='';$('year').value='all';updateSubjects();updatePicker();persist();};host.append(b);});}
function updatePicker(preferredId){const f=state.filters;$('mode').value=f.mode;$('year').value=f.year;$('reference-filter').value=f.reference;const basic=f.mode==='basic';$('year').disabled=basic;$('reference-filter').disabled=basic;$('search').disabled=basic;const list=basic?DATA.basic.filter(q=>q.subject===f.subject):DATA.questions.filter(q=>q.subject===f.subject&&(f.year==='all'||String(q.year)===f.year)&&(f.reference==='all'||q.reference.kind===f.reference)&&(!f.search||[q.title,q.body].some(t=>t.includes(f.search))));const select=$('question-select');const previous=preferredId||select.value;select.replaceChildren();list.forEach(q=>{const s=state.sessions[keyFor(q.id,f.mode)],o=node('option',q.title+(s?' · '+(s.index>=s.rounds.length?'已完成':'已開始'):'')+(q.reference.kind==='requirements'?' · 題幹要求清單':''));o.value=q.id;select.append(o);});if(list.some(q=>q.id===previous))select.value=previous;$('start').disabled=!list.length;$('copy-ai-pack').disabled=!list.length;$('download-ai-pack').disabled=!list.length;$('ai-pack-status').textContent='';$('ai-pack-text').value='';$('ai-pack-fallback').open=false;$('selection-info').textContent=!list.length?'這個範圍沒有題目，請調整搜尋、年度或核對資料。':basic?'補充基礎只練科目作答方法；不對應單一年度原題。':`${list.length} 題符合範圍。${qs.get(select.value).reference.status}`;$('record-count').textContent=`${Object.keys(state.sessions).length} 組已有紀錄`;}
function choose(){const id=$('question-select').value,q=qs.get(id);if(!q)return;const mode=state.filters.mode,key=keyFor(id,mode);if(!state.sessions[key])state.sessions[key]={questionId:id,mode,index:0,paused:false,rounds:getItems(q,mode).map(emptyRound),history:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};state.active=key;persist();render();$('session-area').scrollIntoView({block:'start',behavior:'smooth'});}
for(const [id,field] of [['mode','mode'],['year','year'],['reference-filter','reference']])$(id).onchange=()=>{state.filters[field]=$(id).value;updatePicker();persist();};$('search').oninput=()=>{state.filters.search=$('search').value.trim();updatePicker();persist();};$('question-select').onchange=()=>updatePicker($('question-select').value);$('start').onclick=choose;
function selectedPack(){const q=qs.get($('question-select').value);return q?window.buildRecallAIPack(q,state.filters.mode):'';}
function showPack(text){$('ai-pack-text').value=text;}
$('copy-ai-pack').onclick=async()=>{const text=selectedPack();if(!text)return;showPack(text);try{if(!navigator.clipboard?.writeText)throw Error();await navigator.clipboard.writeText(text);$('ai-pack-status').textContent='已複製！開啟 ChatGPT，貼上並送出，就會從第一題開始。';}catch{$('ai-pack-fallback').open=true;$('ai-pack-text').focus();$('ai-pack-text').select();$('ai-pack-status').textContent='瀏覽器未允許自動複製，請複製下方已選取的文字，或下載文字檔。';}};
$('ai-pack-fallback').ontoggle=()=>{if($('ai-pack-fallback').open)showPack(selectedPack());};
$('download-ai-pack').onclick=()=>{const q=qs.get($('question-select').value),text=selectedPack();if(!text)return;const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=node('a');a.href=url;a.download='AI帶練_'+q.id+'_'+state.filters.mode+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('ai-pack-status').textContent='已準備帶練文字檔；開啟後複製全文，貼到 ChatGPT。';};
function renderSteps(items,s){$('steps').replaceChildren(...items.map((item,i)=>{const li=node('li',item.title,s.index===i&&!s.paused?'current':'');li.append(node('small',s.rounds[i].done?names[s.rounds[i].rating]:(s.index===i?'目前回合':'尚未練習')));return li;}));}
function render(){updatePicker();const s=active(),q=currentQuestion();$('session-area').hidden=!s;if(!s)return;const items=getItems(q,s.mode);renderSteps(items,s);$('active-subject').textContent=q.subject+(q.year?` / ${q.year} 年 / 觀護人`:' / 補充基礎');$('active-title').textContent=q.title;$('reference-status').textContent=q.reference.status;$('parent-question').hidden=!q.year;$('parent-question').open=s.mode==='guided'&&q.id!=='114-心理學-1';$('original-label').textContent=q.originalLabel||'';$('original-body').textContent=q.body;$('source-link').href=q.sourceUrl||'#';$('basis-note').textContent=(q.reference.checkedAt?`既有參考要點查核日：${q.reference.checkedAt}。`:'本題目前沒有內容詳解。')+(q.reference.legal?'法律題另須核對原題年份、現行法與相關實務；本次未逐題新覆核。':'核對整理非官方標準答案。');$('basis-links').replaceChildren(...q.reference.sources.map(source=>{const li=node('li'),a=node('a',source.title);a.href=source.url;a.target='_blank';a.rel='noopener';li.append(a);return li;}));const essay='../v2.5/?q='+encodeURIComponent(q.id);for(const id of ['essay-link','summary-essay']){$(id).hidden=!q.year;$(id).href=essay;}
 if(s.paused||s.index>=items.length){showSummary(q,s,items);return;}$('practice').hidden=false;$('summary').hidden=true;const r=s.rounds[s.index],item=items[s.index];$('round').textContent=`回合 ${s.index+1} / ${items.length}`;$('progress').max=items.length;$('progress').value=s.rounds.filter(r=>r.done).length;$('source-label').textContent=item.label;$('question-heading').textContent=item.prompt;$('scope').textContent=item.scope;$('context-note').textContent=q.year&&s.mode==='guided'?'原題可在上方「查看本題原題與出處」展開；核對要點等作答後才顯示。':'';$('phase-label').textContent=r.hint?'提示後重答':'自行回想';$('answer').value=r.draft;$('answer').disabled=r.phase!=='writing';$('submit').hidden=r.phase!=='writing';$('hint').hidden=r.phase!=='writing'||r.hint;$('hint-panel').hidden=!r.hint;$('hint-text').textContent=item.hint;$('choice-panel').hidden=r.phase!=='submitted';$('answer-panel').hidden=r.phase!=='checking';$('retry').hidden=r.hint||r.attempts.length>=2;$('check').textContent=isRequirements(q)?'核對題幹要求':'核對我的回答';
 if(r.phase==='checking'){$('check-kind').textContent=q.reference.status;$('model-title').textContent=item.model?'精簡考場說法':isRequirements(q)?'先核對本題要求與作答結構':'核對這幾點';$('model').hidden=!item.model;$('model').textContent=item.model||'';$('criteria').replaceChildren(...item.criteria.map(text=>node('li',text)));$('self-note').textContent=isRequirements(q)?'這些項目只能幫你核對作答要求，不能證明概念、法條或結論正確。內容尚未查核時，請選「內容待核對」。':'這是自我核對，不是系統正確性判定。看過要點才補足的內容，請標記需要再練。';document.querySelectorAll('[data-rating]').forEach(b=>{b.disabled=b.dataset.rating==='independent'&&(r.hint||r.attempts.length>1||isRequirements(q));b.setAttribute('aria-pressed',String(b.dataset.rating===r.rating));});$('note').value=r.note||'';$('verify-note').value=r.verifyNote||'';$('rating-status').textContent=r.rating?'本回合標記：'+names[r.rating]:'請選擇一個狀態，再繼續。';$('next').disabled=!r.rating;$('next').textContent=s.index===items.length-1?'記錄並查看本輪小結':'記錄並繼續';}persist();}
function hint(){const s=active(),r=s.rounds[s.index];if(r.phase==='checking')return;r.hint=true;r.phase='writing';r.rating=null;s.updatedAt=new Date().toISOString();persist();render();$('answer').focus();}
$('answer').oninput=()=>{const s=active();s.rounds[s.index].draft=$('answer').value;s.updatedAt=new Date().toISOString();$('answer').setCustomValidity('');persist();};
$('answer-form').onsubmit=e=>{e.preventDefault();const s=active(),r=s.rounds[s.index];if(r.phase!=='writing')return;const text=$('answer').value.trim();if(!text){$('answer').setCustomValidity('先寫一句回答；卡住時可以先看提示。');$('answer').reportValidity();return;}r.draft=text;r.attempts.push({text,hint:r.hint,at:new Date().toISOString()});r.phase=r.attempts.length>=2?'checking':'submitted';r.rating=null;s.updatedAt=new Date().toISOString();persist();render();(r.phase==='checking'?$('answer-panel'):$('choice-panel')).scrollIntoView({block:'nearest'});};
$('hint').onclick=hint;$('retry').onclick=hint;$('check').onclick=()=>{active().rounds[active().index].phase='checking';persist();render();};
document.querySelectorAll('[data-rating]').forEach(b=>b.onclick=()=>{const s=active(),r=s.rounds[s.index];if(r.phase!=='checking')return;r.rating=b.dataset.rating;s.updatedAt=new Date().toISOString();persist();render();});
for(const [id,field] of [['note','note'],['verify-note','verifyNote']])$(id).oninput=()=>{active().rounds[active().index][field]=$(id).value;active().updatedAt=new Date().toISOString();persist();};
$('next').onclick=()=>{const s=active(),r=s.rounds[s.index];if(!r.rating)return;r.done=true;r.completedAt=new Date().toISOString();const remaining=s.rounds.findIndex((r,i)=>i>s.index&&!r.done);s.index=remaining<0?s.rounds.length:remaining;s.updatedAt=new Date().toISOString();persist();render();(s.index<s.rounds.length?$('question-heading'):$('summary-heading')).focus();};
$('pause').onclick=()=>{active().paused=true;persist();render();$('summary-heading').focus();};
function showSummary(q,s,items){$('practice').hidden=true;$('summary').hidden=false;$('summary-count').textContent=`已核對 ${s.rounds.filter(r=>r.done).length} / ${items.length} 回合；以下依你的紀錄整理，不是 AI 評答。`;const stable=[],again=[],verify=[],notes=[];s.rounds.forEach((r,i)=>{if(r.done&&r.rating==='independent')stable.push(items[i].title);if(r.done&&['prompted','review'].includes(r.rating))again.push(items[i].gap||items[i].title);if(r.done&&r.rating==='verify')verify.push(items[i].title);if(r.note)notes.push(r.note);if(r.verifyNote)verify.push(r.verifyNote);});if(isRequirements(q))verify.push('本題尚無內容答案；需對照教材或可靠來源查核。');if(q.reference.legal)verify.push('法條與實務：核對原題年份及現行版本。');const next=s.rounds.findIndex(r=>r.done&&r.rating!=='independent'),pending=s.rounds.findIndex(r=>!r.done);const sections=[['自行回想完成',stable.join('、')||'本次無；尚未核對的回合不列為已掌握。'],['需再提取',again.join('、')||'本次無。'],['容易混淆','本次無自動判定；可在待查證欄記下自己察覺的區別。'],['筆記待補',notes.join('；')||'本次無。'],['待查證',[...new Set(verify)].join('；')||'本次無新增項目。'],['下一輪起手題',next>=0?(items[next].gap||items[next].title):pending>=0?items[pending].title:q.year?'回到同一道原題，檢查完整申論。':'選這一科的一道原題，把骨架用到內容。']];$('summary-body').replaceChildren(...sections.map(([title,text])=>{const section=node('section');section.append(node('h3',title),node('p',text));return section;}));$('resume').hidden=s.index>=items.length;$('review').hidden=!s.rounds.some(r=>r.done&&r.rating!=='independent');$('attempt-log').replaceChildren(...s.rounds.map((r,i)=>{const section=node('section');section.append(node('h3',items[i].title));r.attempts.forEach((a,j)=>section.append(node('p',`第 ${j+1} 次${a.hint?'（已看提示）':''}：${a.text}`)));if(!r.attempts.length)section.append(node('p','尚未作答'));return section;}));}
function archive(reason){const s=active();s.history.push({reason,at:new Date().toISOString(),rounds:clone(s.rounds)});}
$('resume').onclick=()=>{active().paused=false;persist();render();$('question-heading').focus();};
$('review').onclick=()=>{const s=active(),indexes=s.rounds.flatMap((r,i)=>r.done&&r.rating!=='independent'?[i]:[]);if(!indexes.length)return;archive('review');indexes.forEach(i=>s.rounds[i]=emptyRound());s.index=indexes[0];s.paused=false;s.updatedAt=new Date().toISOString();persist();render();$('question-heading').focus();};
$('restart').onclick=()=>{archive('restart');const s=active();s.rounds=getItems(currentQuestion(),s.mode).map(emptyRound);s.index=0;s.paused=false;s.updatedAt=new Date().toISOString();persist();render();$('question-heading').focus();};
$('export').onclick=()=>{const payload={format:'probation-active-recall',version:2,exportedAt:new Date().toISOString(),scope:DATA.scope,assessment:'self-check',state};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download='觀護人各科主動回憶_'+new Date().toLocaleDateString('sv-SE')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('import').onclick=()=>$('import-file').click();
$('import-file').onchange=async()=>{const file=$('import-file').files[0];if(!file)return;try{if(file.size>10000000)throw Error();const data=JSON.parse(await file.text());let incoming=data.state;if(data.format!=='probation-active-recall')throw Error();if(data.version===1&&incoming?.version===1){const old=incoming;incoming=newStore();const key=keyFor('114-心理學-1','guided');incoming.sessions[key]={questionId:'114-心理學-1',mode:'guided',index:old.index,paused:old.paused,rounds:old.rounds.map(r=>({...emptyRound(),...r})),history:old.history||[],updatedAt:old.updatedAt||old.createdAt};}if(!validStore(incoming))throw Error();let added=0,kept=0,unchanged=0;for(const [key,session] of Object.entries(incoming.sessions)){const existing=state.sessions[key];if(!existing){state.sessions[key]=clone(session);added++;}else if(JSON.stringify(existing.rounds)===JSON.stringify(session.rounds)||existing.history.some(h=>JSON.stringify(h.rounds)===JSON.stringify(session.rounds))){unchanged++;}else{existing.history.push({reason:'import-kept-copy',at:new Date().toISOString(),rounds:clone(session.rounds)});kept++;}}persist();updatePicker();render();notice(`已加入 ${added} 組；${kept} 組同題副本存入歷史，現有進度保留；${unchanged} 組相同紀錄不重複加入。`);}catch{notice('無法匯入：檔案格式、題目或回合狀態不相容。現有紀錄未更動。');}$('import-file').value='';};
load();for(let year=115;year>=108;year--){const o=node('option',year+' 年');o.value=String(year);$('year').append(o);}if(!DATA.subjects.some(s=>s.name===state.filters.subject))state.filters.subject='心理學';if(!['guided','original','basic'].includes(state.filters.mode))state.filters.mode='guided';$('search').value=state.filters.search||'';$('coverage').textContent=`六科 · ${DATA.questions.length} 道原題 · ${DATA.questions.filter(q=>q.reference.kind==='outline').length} 題附既有參考要點 · ${DATA.questions.filter(q=>q.reference.kind==='requirements').length} 題附題幹要求清單`;
const requested=new URLSearchParams(location.search).get('q');if(requested&&qs.has(requested)){state.filters.subject=qs.get(requested).subject;state.filters.year='all';state.filters.search='';state.filters.reference='all';state.filters.mode=qs.get(requested).year?'guided':'basic';$('search').value='';updateSubjects();updatePicker(requested);choose();}else{updateSubjects();updatePicker();render();}persist();
})();
