'use strict';
const M=window.PracticeModel,$=id=>document.getElementById(id),KEY='probation-daily-github:records:v1',SAVED='daily-reading-test:saved',DATA='daily-reading-test:dataset';
const order=['犯罪學','心理學','諮商與輔導','少年事件處理法','保安處分執行法','刑事訴訟法','跨科整合'];
let data=null,records={},saved=[],current='',writable=true,source='正式每日題庫',loading=false;
const initialParams=new URLSearchParams(location.search);
const state={tab:initialParams.get('subject')?'全部題目':'晚間摘要／新聞',subject:initialParams.get('subject')||'',date:'',query:'',sort:'newest'};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const time=s=>{const d=new Date(s);return Number.isNaN(d.getTime())?'未提供日期':d.toLocaleString('zh-TW',{timeZone:'Asia/Taipei',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});};
const notify=s=>{$('notice').textContent=s;};
try{records=M.records(JSON.parse(localStorage.getItem(KEY)||'{}'));const v=JSON.parse(localStorage.getItem(SAVED)||'[]');saved=Array.isArray(v)?v.filter(x=>typeof x==='string'):[];}catch{writable=false;notify('原本機紀錄無法讀取，已保留原資料。本次作答僅暫存，請匯出備份。');}
function persist(next=records){if(!writable)throw Error('本機儲存不可用，請先匯出備份');localStorage.setItem(KEY,JSON.stringify(next));}
function visible(){return M.filter(data?.questions||[],records,saved,state);}
function menu(close=true){$('sidebar').classList.toggle('is-open',!close);$('scrim').hidden=close;$('menu').setAttribute('aria-expanded',String(!close));}
function choose(tab,subject=''){state.tab=tab;state.subject=subject;render();menu();}
function toggleSaved(id){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];try{localStorage.setItem(SAVED,JSON.stringify(saved));}catch{notify('收藏目前只保留於本次開啟期間；瀏覽器無法保存。');}render();if($('reader').open)bookmark();}
function bookmark(){const yes=saved.includes(current);$('bookmark').textContent=yes?'★':'☆';$('bookmark').setAttribute('aria-label',yes?'取消收藏本題':'收藏本題');$('bookmark').setAttribute('aria-pressed',String(yes));}
function render(){
 const qs=data?.questions||[],subjects=[...new Set(qs.map(M.subject))].sort((a,b)=>{const r=x=>order.includes(x)?order.indexOf(x):order.length;return r(a)-r(b)||a.localeCompare(b,'zh-TW');});
 $('total').textContent=qs.length;$('written').textContent=qs.filter(q=>records[q.id]?.answer.trim()).length;$('reviewCount').textContent=qs.filter(q=>records[q.id]?.review).length;$('updated').textContent=time(data?.updatedAt);$('dataSource').textContent=source+'・台灣時間';$('start').disabled=false;
 $('nav').innerHTML=[...ReadingNews.tabs,'全部題目','已有作答','待複習','我的收藏'].map(t=>{const reading=ReadingNews.isReading(t);const n=reading?ReadingNews.count(t):t==='全部題目'?qs.length:t==='已有作答'?qs.filter(q=>records[q.id]?.answer.trim()).length:t==='待複習'?qs.filter(q=>records[q.id]?.review).length:qs.filter(q=>saved.includes(q.id)).length;return `<button class="nav-item ${state.tab===t?'active':''}" data-tab="${t}"><span class="symbol">${reading?'▤':'✎'}</span><span>${t==='全部題目'?'每日模擬題':t==='我的收藏'?'題目收藏':t}</span><small>${n}</small></button>`;}).join('');
 $('backupPanel').hidden=ReadingNews.isReading(state.tab);
 if(ReadingNews.isReading(state.tab)){ReadingNews.render(state);return;}
 if(!qs.length){$('heading').textContent='每日模擬題';$('cards').innerHTML='<div class="empty"><h3>題庫尚未載入</h3><p>請確認 questions.json 存在，並按更新題庫重試。</p></div>';$('latest').hidden=true;$('start').disabled=true;return;}
 $('total').nextElementSibling.textContent='已收錄模擬題';$('written').nextElementSibling.textContent='已有作答';$('reviewCount').nextElementSibling.textContent='待複習題目';$('search').placeholder='搜尋案例、考點或理論，例如：標籤、榮格…';const hero=$('start').closest('.hero').querySelector('h1');hero.innerHTML='留一點時間，<br>把理解寫成<span>答案。</span>';hero.nextElementSibling.innerHTML='從一個少年個案開始，練習理論、涵攝與處遇。<br>先寫自己的答案，再打開參考架構。';$('start').textContent='開始最新一題 →';$('notice').textContent='作答自動保存在目前瀏覽器；參考架構預設收合。更新題庫會載入已同步的每日模擬題。';
 $('subjects').innerHTML=subjects.map((s,i)=>`<button class="${state.subject===s?'selected':''}" data-subject="${esc(s)}"><span class="subject-dot dot-${i%4}"></span>${esc(s)}<span style="margin-left:auto">›</span></button>`).join('');
 $('tags').innerHTML=['',...subjects].map(s=>`<button class="${state.subject===s?'chosen':''}" data-subject="${esc(s)}">${esc(s||'全部科目')}</button>`).join('');
 const dates=[...new Set(qs.map(q=>q.date))].sort().reverse();$('date').innerHTML='<option value="">所有日期</option>'+dates.map(d=>`<option value="${d}">${d}</option>`).join('');$('date').value=state.date;
 $('heading').textContent=state.subject||state.tab;$('breadcrumb').textContent=state.subject||state.tab;
 const list=visible();$('resultCount').textContent=`共 ${list.length} 題`;
 $('cards').innerHTML=list.length?list.map(q=>{const r=records[q.id],status=r?.review?'★ 待複習':r?.answer.trim()?'已有作答':'尚未作答';return `<article class="document-card"><div class="card-top"><span class="document-date">${esc(q.date)}</span><button class="icon-button bookmark ${saved.includes(q.id)?'bookmarked':''}" data-save="${esc(q.id)}" aria-label="${saved.includes(q.id)?'取消收藏':'收藏本題'}">${saved.includes(q.id)?'★':'☆'}</button></div><button class="card-content" data-open="${esc(q.id)}"><h3>${esc(M.title(q))}</h3><p>${esc(M.excerpt(q.issues||q.question).slice(0,130))}</p></button><div class="card-tags"><button data-subject="${esc(M.subject(q))}">${esc(M.subject(q))}</button><button data-open="${esc(q.id)}">待內容核對</button></div><div class="card-footer"><span class="${r?.review?'marked':''}">${status}</span><button data-open="${esc(q.id)}">${r?.answer.trim()?'繼續練習':'開始作答'} →</button></div></article>`;}).join(''):'<div class="empty"><h3>沒有符合條件的題目</h3><p>試試其他考點，或按「清除篩選」。</p></div>';
 const newest=[...qs].sort((a,b)=>b.date.localeCompare(a.date)||a.id.localeCompare(b.id));$('latest').hidden=state.tab!=='全部題目'||!!state.subject||!!state.query||!!state.date;
 const first=newest[0];$('latest').innerHTML=`<div class="section-heading"><div><span class="eyebrow">THE LATEST PRACTICE</span><h2>最近練習題</h2></div><span>${first.date}</span></div><div class="latest-grid"><button class="featured-card" data-open="${esc(first.id)}"><div class="featured-top"><span class="pill">最新題目</span><span>${esc(M.subject(first))}</span></div><h3>${esc(M.title(first))}</h3><p>${esc(M.excerpt(first.question).slice(0,150))}</p><div class="featured-footer"><span>先寫答案，再看架構</span><span class="round-arrow">↗</span></div></button><div class="latest-stack">${newest.slice(1,4).map(q=>`<button class="compact-card" data-open="${esc(q.id)}"><span class="compact-icon">✎</span><div><small>${esc(q.date)} · ${esc(M.subject(q))}</small><h3>${esc(M.title(q))}</h3></div><span>↗</span></button>`).join('')}</div></div>`;
}
function markdown(text){const lines=String(text||'').split('\n');let out='',table=[];const flush=()=>{if(!table.length)return;const rows=table.filter(r=>!r.every(c=>/^:?-+:?$/.test(c.replace(/\s/g,''))));out+='<div class="table-wrap"><table>'+rows.map((r,i)=>'<tr>'+r.map(c=>`<${i?'td':'th'}>${esc(c)}</${i?'td':'th'}>`).join('')+'</tr>').join('')+'</table></div>';table=[];};for(const line of lines){if(/^\s*\|/.test(line)){table.push(line.trim().replace(/^\||\|$/g,'').split('|').map(c=>c.trim()));continue;}flush();const h=line.match(/^#{1,6}\s+(.*)/);if(h)out+='<h3>'+esc(h[1])+'</h3>';else if(line.trim())out+='<p>'+esc(line)+'</p>';}flush();return out;}
function section(title,body){return `<details><summary>${esc(title)}</summary>${body}</details>`;}
function openQuestion(id){
 const q=data.questions.find(q=>q.id===id);if(!q)return;current=id;const r=records[id];$('reader-title').textContent=M.title(q);$('readerMeta').textContent=`${q.date} · ${M.subject(q)} · 待內容核對`;$('prompt').textContent=q.question;$('answer').value=r?.answer||'';$('review').checked=!!r?.review;$('wordCount').textContent=$('answer').value.length+' 字';$('draftStatus').textContent=r?.updatedAt?'上次作答：'+time(r.updatedAt):'尚未作答・輸入後自動儲存';$('changedNotice').hidden=!r?.questionSnapshot||r.questionSnapshot===M.signature(q);bookmark();
 const table=q.theoryTable.length?'<div class="table-wrap"><table>'+q.theoryTable.map((row,i)=>'<tr>'+row.map(c=>`<${i?'td':'th'}>${esc(c)}</${i?'td':'th'}>`).join('')+'</tr>').join('')+'</table></div>':'<p>來源未提供完整四欄表，待補。</p>';
 const template=(data.templates||[]).find(t=>t.subject===M.subject(q));
 $('references').innerHTML=section('核心爭點與複習方向',`<div class="reference-text">${esc(q.issues||'來源未提供，待補充。')}</div>`)+section('參考答題架構',`<div class="reference-text">${esc(q.outline||'來源未提供，待補充。')}</div>`)+section('理論與少年個案應用四欄表',table)+(q.studyNotes?section('易錯提醒與處遇重點',`<div class="reference-text">${esc(q.studyNotes)}</div>`):'')+section('原始考題出處',`<div class="reference-text">${esc(q.sourceReference||'來源尚未提供獨立出處，待核對。')}<p>出處依來源標示，尚未核對官方原卷。</p></div>`)+(template?section('答題模板',markdown(template.content)):'');
 const list=visible(),i=list.findIndex(x=>x.id===id);$('position').textContent=i>=0?`${i+1} / ${list.length}`:'目前篩選外的題目';$('previous').disabled=i<=0;$('next').disabled=i<0||i>=list.length-1;
 $('readerScroll').scrollTop=0;if(!$('reader').open){$('reader').showModal();document.body.classList.add('modal-open');$('close').focus();}
}
function save(){const q=data.questions.find(q=>q.id===current);if(!q)return;records[current]={...records[current],answer:$('answer').value,review:$('review').checked,updatedAt:new Date().toISOString(),questionSnapshot:M.signature(q)};$('wordCount').textContent=$('answer').value.length+' 字';try{persist();$('draftStatus').textContent='已自動儲存於此瀏覽器 · '+time(records[current].updatedAt);}catch{$('draftStatus').textContent='僅暫存於此頁，請匯出備份';}render();}
async function readJSON(url){const r=await fetch(url,{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('HTTP '+r.status);return M.dataset(await r.json());}
async function load(live=false){if(loading)return;loading=true;$('refresh').disabled=true;$('refresh').textContent='正在讀取…';try{if(live){const next=await readJSON('./questions.json');data=next;source='手動更新的正式題庫';try{localStorage.setItem(DATA,JSON.stringify(data));}catch{}notify('已載入 '+data.count+' 題；原作答保留。');}else{try{data=await readJSON('./questions.json');source='正式每日題庫';}catch(e){const cached=localStorage.getItem(DATA);if(!cached)throw e;data=M.dataset(JSON.parse(cached));source='上次成功讀取的題庫';}}render();if(current&&$('reader').open)openQuestion(current);}catch(e){notify((live?'無法取得正式站新題庫，保留目前題目與作答。':'載入題庫失敗，請重新整理。')+' '+e.message);}finally{loading=false;$('refresh').disabled=false;$('refresh').textContent='↻ 更新題庫';}}
function download(d,name){const url=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.docOpen)ReadingNews.open(b.dataset.docOpen);else if(b.dataset.docSave)ReadingNews.mark(b.dataset.docSave,'saved');else if(b.dataset.docRead)ReadingNews.mark(b.dataset.docRead,'read');else if(b.dataset.open)openQuestion(b.dataset.open);else if(b.dataset.save)toggleSaved(b.dataset.save);else if(b.dataset.tab)choose(b.dataset.tab);else if(b.dataset.subject!==undefined)choose(ReadingNews.isReading(state.tab)?state.tab:'全部題目',b.dataset.subject);});
$('search').oninput=()=>{state.query=$('search').value.trim();render();};$('date').onchange=()=>{state.date=$('date').value;render();};$('sort').onchange=()=>{state.sort=$('sort').value;render();};$('clearFilters').onclick=()=>{Object.assign(state,{tab:ReadingNews.isReading(state.tab)?'晚間摘要／新聞':'全部題目',subject:'',date:'',query:'',sort:'newest'});$('search').value='';$('sort').value='newest';render();};
$('refresh').onclick=()=>ReadingNews.isReading(state.tab)?ReadingNews.load():load(true);$('start').onclick=()=>{if(ReadingNews.isReading(state.tab)){const d=ReadingNews.latest();if(d)ReadingNews.open(d.id);return;}const q=[...data.questions].sort((a,b)=>b.date.localeCompare(a.date)||a.id.localeCompare(b.id))[0];openQuestion(q.id);};$('menu').onclick=()=>menu(false);$('scrim').onclick=()=>menu();document.addEventListener('keydown',e=>{if(e.key==='Escape')menu();});
$('close').onclick=()=>$('reader').close();$('reader').addEventListener('close',()=>document.body.classList.remove('modal-open'));$('reader').addEventListener('click',e=>{if(e.target===$('reader'))$('reader').close();});$('bookmark').onclick=()=>toggleSaved(current);$('answer').oninput=save;$('review').onchange=save;
for(const [id,delta] of [['previous',-1],['next',1]])$(id).onclick=()=>{const list=visible(),i=list.findIndex(q=>q.id===current),q=list[i+delta];if(q)openQuestion(q.id);};
$('export').onclick=()=>{if($('reader').open)save();download({format:'probation-daily-github-records',schemaVersion:1,exportedAt:new Date().toISOString(),records},'daily-simulation-records-'+new Date().toISOString().slice(0,10)+'.json');notify('已匯出每日學習室的每日模擬題作答，可匯回 v2.5；收藏不包含在作答備份。');};
$('import').onclick=()=>$('upload').click();$('upload').onchange=async()=>{try{const file=$('upload').files[0];if(!file)return;if(file.size>4*1024*1024)throw Error('檔案超過4MB');const incoming=M.backup(JSON.parse(await file.text())),n=Object.keys(incoming).length;if(!n)throw Error('備份中沒有每日模擬題作答');const matched=Object.keys(incoming).filter(id=>data.questions.some(q=>q.id===id)).length;if(!confirm(`匯入 ${n} 筆每日模擬題作答，其中 ${matched} 筆對應目前題庫。同題以備份內容為主，現有紀錄先保留一份備份。考古題紀錄不匯入此每日學習室。是否繼續？`))return;if($('reader').open)save();localStorage.setItem('daily-reading-test:before-import',JSON.stringify(records));const next={...records,...incoming};persist(next);records=next;render();if(current&&$('reader').open)openQuestion(current);notify(`已匯入 ${n} 筆每日模擬題作答；${matched} 筆對應目前題庫。其餘紀錄也保留於匯出檔。`);}catch(e){notify('匯入未完成：'+e.message);}finally{$('upload').value='';}};
$('clearRecords').onclick=()=>{const n=Object.keys(records).length;if(!n){notify('每日學習室目前沒有作答紀錄。');return;}if(!confirm(`清除每日學習室全部 ${n} 筆作答與待複習標記？考古題練習紀錄不受影響。清除前會先下載一份備份。`))return;download({format:'probation-daily-github-records',schemaVersion:1,exportedAt:new Date().toISOString(),records},'daily-records-before-clear.json');try{persist({});records={};render();if(current&&$('reader').open)openQuestion(current);notify('每日學習室作答已清除。收藏仍保留；請確認剛才下載的備份。');}catch(e){notify('未完成清除：'+e.message);}};
window.addEventListener('storage',e=>{if(e.key===KEY){try{records=M.records(JSON.parse(e.newValue||'{}'));render();if(current&&$('reader').open)openQuestion(current);}catch{notify('另一分頁的紀錄格式不符，未套用。');}}});
ReadingNews.init(render).then(()=>{const id=initialParams.get('document');if(id){state.tab='全部閱讀資料';state.subject='';render();ReadingNews.open(id);}});load();
