(function(root){
 'use strict';
 const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const tabs=['晚間摘要／新聞','全部閱讀資料','閱讀收藏','未讀資料'];
 const time=s=>new Date(s).toLocaleString('zh-TW',{timeZone:'Asia/Taipei',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false});
 const readLocal=k=>{try{const v=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(v)?v.filter(x=>typeof x==='string'):[];}catch{return [];}};
 let docs=[],sync=null,loading=true,error='',saved=readLocal('daily-reading-test:news-saved'),read=readLocal('daily-reading-test:news-read'),selected='',rerender=()=>{};
 const url=s=>{try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}};
 function inline(s){const parts=String(s).split(/(\[[^\]\n]+\]\([^\s)]+\)|https?:\/\/[^\s<>]+|\*\*[^*\n]+\*\*|`[^`\n]+`)/g);return parts.map(p=>{const link=p.match(/^\[([^\]]+)\]\(([^)]+)\)$/);if(link){const u=url(link[2]);return u?`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(link[1])}</a>`:esc(p);}if(/^https?:\/\//.test(p)){const u=url(p);return u?`<a href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(p)}</a>`:esc(p);}if(/^\*\*.*\*\*$/.test(p))return '<strong>'+esc(p.slice(2,-2))+'</strong>';if(/^`.*`$/.test(p))return '<code>'+esc(p.slice(1,-1))+'</code>';return esc(p);}).join('');}
 function markdown(text){let html='',rows=[],paragraph=[],list='',fence=false,code=[];const flushP=()=>{if(paragraph.length){html+='<p>'+paragraph.map(inline).join('<br>')+'</p>';paragraph=[];}};const flushL=()=>{if(list){html+='</'+list+'>';list='';}};const flushT=()=>{if(rows.length){const valid=rows.filter(r=>!r.every(c=>/^:?-+:?$/.test(c.replace(/\s/g,''))));html+='<div class="table-wrap"><table>'+valid.map((r,i)=>'<tr>'+r.map(c=>`<${i?'td':'th'}>${inline(c)}</${i?'td':'th'}>`).join('')+'</tr>').join('')+'</table></div>';rows=[];}};
 for(const line of String(text).split('\n')){if(/^\s*```/.test(line)){flushP();flushL();flushT();if(fence){html+='<pre><code>'+esc(code.join('\n'))+'</code></pre>';code=[];}fence=!fence;continue;}if(fence){code.push(line);continue;}if(/^\s*\|.*\|\s*$/.test(line)){flushP();flushL();rows.push(line.trim().slice(1,-1).split(/(?<!\\)\|/).map(c=>c.trim().replace(/\\\|/g,'|')));continue;}flushT();if(!line.trim()){flushP();flushL();continue;}const h=line.match(/^(#{1,6})\s+(.+)$/);if(h){flushP();flushL();html+=`<h${h[1].length}>${inline(h[2])}</h${h[1].length}>`;continue;}if(/^\s*(---+|\*\*\*+)\s*$/.test(line)){flushP();flushL();html+='<hr>';continue;}const li=line.match(/^\s*(?:([-*])|(\d+)\.)\s+(.+)$/);if(li){flushP();const kind=li[2]?'ol':'ul';if(list!==kind){flushL();html+='<'+kind+'>';list=kind;}html+='<li>'+inline(li[3])+'</li>';continue;}if(/^>\s?/.test(line)){flushP();flushL();html+='<blockquote>'+inline(line.replace(/^>\s?/,''))+'</blockquote>';continue;}flushL();paragraph.push(line);}
 flushP();flushL();flushT();if(code.length)html+='<pre><code>'+esc(code.join('\n'))+'</code></pre>';return html;}
 function valid(v){if(!v||!Array.isArray(v.documents)||!v.documents.every(d=>typeof d.id==='string'&&typeof d.title==='string'&&typeof d.content==='string'&&Array.isArray(d.tags)&&d.tags.every(x=>typeof x==='string')&&typeof d.date==='string'&&typeof d.modified==='string'&&url(d.url)))throw Error('閱讀資料格式不符');return v;}
 function filter(s){return docs.filter(d=>(s.tab!=='晚間摘要／新聞'||d.tags.includes('晚間摘要')||/新聞/.test(d.title))&&(s.tab!=='閱讀收藏'||saved.includes(d.id))&&(s.tab!=='未讀資料'||!read.includes(d.id))&&(!s.subject||d.tags.includes(s.subject))&&(!s.date||d.date===s.date)&&(!s.query||(d.title+' '+d.content).toLowerCase().includes(s.query.toLowerCase()))).sort((a,b)=>s.sort==='oldest'?a.date.localeCompare(b.date)||a.modified.localeCompare(b.modified):b.date.localeCompare(a.date)||b.modified.localeCompare(a.modified));}
 function card(d){return `<article class="document-card ${read.includes(d.id)?'is-read':''}"><div class="card-top"><span class="document-date">${esc(d.date)}</span><button class="icon-button bookmark ${saved.includes(d.id)?'bookmarked':''}" data-doc-save="${esc(d.id)}" aria-label="${saved.includes(d.id)?'取消收藏文件':'收藏文件'}">${saved.includes(d.id)?'★':'☆'}</button></div><button class="card-content" data-doc-open="${esc(d.id)}"><h3>${esc(d.title.replace(/\.md$/i,''))}</h3><p>${esc(d.excerpt||d.content.slice(0,130))}</p></button><div class="card-tags">${d.tags.slice(0,3).map(t=>`<button data-subject="${esc(t)}">${esc(t)}</button>`).join('')}</div><div class="card-footer"><button data-doc-read="${esc(d.id)}" class="${read.includes(d.id)?'marked':''}">${read.includes(d.id)?'✓ 已讀':'標記已讀'}</button><button data-doc-open="${esc(d.id)}">開始閱讀 →</button></div></article>`;}
 function render(s){
 $('heading').textContent=s.subject||s.tab;$('breadcrumb').textContent=s.subject||s.tab;$('total').textContent=docs.length;$('written').textContent=docs.filter(d=>read.includes(d.id)).length;$('reviewCount').textContent=docs.filter(d=>saved.includes(d.id)).length;
 $('total').nextElementSibling.textContent='已收錄閱讀文件';$('written').nextElementSibling.textContent='我的已讀資料';$('reviewCount').nextElementSibling.textContent='我的閱讀收藏';$('updated').textContent=sync?.syncedAt?time(sync.syncedAt):'尚未同步';$('dataSource').textContent='上次新聞同步・台灣時間';
 $('search').placeholder='搜尋新聞、司法動態、考點或文件全文…';$('refresh').textContent='↻ 重新讀取資料';$('notice').textContent=error||(sync?.syncedAt?'新聞資料最後同步：'+time(sync.syncedAt)+'（台灣時間）'+(sync.status==='partial'?'・部分文件未更新，已保留上一版。':'。')+'重新讀取會載入已同步的文件。':'尚未設定新聞全文同步。請依安裝教學設定公開資料夾並執行同步；每日模擬題可正常使用。');
 const title=$('start').closest('.hero').querySelector('h1');title.innerHTML='留一點時間，<br>給今天的<span>新知識。</span>';title.nextElementSibling.innerHTML='司法動態、少年司法與觀護人考試。<br>閱讀完整摘要，再切換到每日申論練習。';$('start').textContent='閱讀最新資料 →';$('start').disabled=!docs.length;
 const tags=[...new Set(docs.flatMap(d=>d.tags))].filter(t=>!['晚間摘要','考試專區'].includes(t));$('tags').innerHTML=['',...tags].map(t=>`<button class="${s.subject===t?'chosen':''}" data-subject="${esc(t)}">${esc(t||'全部主題')}</button>`).join('');$('subjects').innerHTML=tags.map((t,i)=>`<button class="${s.subject===t?'selected':''}" data-subject="${esc(t)}"><span class="subject-dot dot-${i%4}"></span>${esc(t)}<span style="margin-left:auto">›</span></button>`).join('');
 const dates=[...new Set(docs.map(d=>d.date))].sort().reverse();$('date').innerHTML='<option value="">所有日期</option>'+dates.map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join('');$('date').value=s.date;
 const list=filter(s);$('resultCount').textContent=`共 ${list.length} 份資料`;$('cards').innerHTML=list.length?list.map(card).join(''):`<div class="empty"><h3>${loading?'正在開啟閱讀資料…':error?'閱讀資料載入失敗':'沒有符合條件的資料'}</h3><p>${error?'請按「重新讀取資料」重試。':'試試其他關鍵字，或清除篩選。'}</p></div>`;
 const latest=filter({...s,tab:'全部閱讀資料',query:'',date:'',subject:'',sort:'newest'});$('latest').hidden=!latest.length||!!s.query||!!s.date||!!s.subject||!['晚間摘要／新聞','全部閱讀資料'].includes(s.tab);
 if(latest.length){const first=latest[0];$('latest').innerHTML=`<div class="section-heading"><div><span class="eyebrow">THE LATEST EDITION</span><h2>最近更新</h2></div><span>${esc(first.date)}</span></div><div class="latest-grid"><button class="featured-card" data-doc-open="${esc(first.id)}"><div class="featured-top"><span class="pill">最新一期</span><span>完整原文</span></div><h3>${esc(first.title.replace(/\.md$/i,''))}</h3><p>${esc(first.excerpt)}</p><div class="featured-footer"><span>新聞整理・觀護人考試</span><span class="round-arrow">↗</span></div></button><div class="latest-stack">${latest.slice(1,4).map(d=>`<button class="compact-card" data-doc-open="${esc(d.id)}"><span class="compact-icon">▤</span><div><small>${esc(d.date)}</small><h3>${esc(d.title.replace(/\.md$/i,''))}</h3></div><span>↗</span></button>`).join('')}</div></div>`;}
 }
 function mark(id,kind){const key=kind==='saved'?'daily-reading-test:news-saved':'daily-reading-test:news-read',list=kind==='saved'?saved:read,next=list.includes(id)?list.filter(x=>x!==id):[...list,id];if(kind==='saved')saved=next;else read=next;try{localStorage.setItem(key,JSON.stringify(next));}catch{$('notice').textContent='瀏覽器無法保存閱讀標記，目前僅暫存於本次開啟期間。';}rerender();if($('newsReader').open)toolbar();}
 function toolbar(){$('newsBookmark').textContent=saved.includes(selected)?'★':'☆';$('newsBookmark').setAttribute('aria-label',saved.includes(selected)?'取消收藏文件':'收藏文件');$('newsRead').textContent=read.includes(selected)?'✓ 已讀完成（點擊取消）':'標記為已讀';}
 function open(id){const d=docs.find(d=>d.id===id);if(!d)return;selected=id;$('newsTitle').textContent=d.title.replace(/\.md$/i,'');$('newsMeta').textContent=d.date+' · 完整原文';$('newsTags').innerHTML=d.tags.map(t=>'<span>'+esc(t)+'</span>').join('');$('newsContent').innerHTML=markdown(d.content);$('newsSource').href=url(d.url);$('newsModified').textContent='原始檔最後修改：'+time(d.modified)+' · 台灣時間';toolbar();$('newsScroll').scrollTop=0;$('newsReader').showModal();document.body.classList.add('modal-open');$('newsClose').focus();}
 async function load(){loading=true;error='';try{const r=await fetch('./documents.json',{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('HTTP '+r.status);const v=valid(await r.json());docs=v.documents;sync=v.sync;}catch(e){error='讀取閱讀資料失敗：'+e.message+'。已有資料保留。';}finally{loading=false;rerender();}}
 root.ReadingNews={tabs,isReading:t=>tabs.includes(t),render,open,mark,load,filter,markdown,inline,valid,count:t=>t==='晚間摘要／新聞'?docs.filter(d=>d.tags.includes('晚間摘要')||/新聞/.test(d.title)).length:t==='閱讀收藏'?docs.filter(d=>saved.includes(d.id)).length:t==='未讀資料'?docs.filter(d=>!read.includes(d.id)).length:docs.length,latest:()=>filter({tab:'全部閱讀資料',sort:'newest'})[0],init(fn){rerender=fn;$('newsClose').onclick=()=>$('newsReader').close();$('newsReader').addEventListener('close',()=>document.body.classList.remove('modal-open'));$('newsReader').addEventListener('click',e=>{if(e.target===$('newsReader'))$('newsReader').close();});$('newsBookmark').onclick=()=>mark(selected,'saved');$('newsRead').onclick=()=>mark(selected,'read');return load();}};
})(window);
