(function(root){
 'use strict';const forbidden=new Set(['__proto__','constructor','prototype']),clone=x=>JSON.parse(JSON.stringify(x));
 function safe(value,depth=0){if(depth>35)return false;if(value===null||['string','number','boolean'].includes(typeof value))return true;if(typeof value!=='object')return false;return Object.entries(value).every(([key,v])=>!forbidden.has(key)&&safe(v,depth+1));}
 function records(value){return value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length<=3000&&safe(value)&&Object.values(value).every(v=>v&&typeof v==='object'&&!Array.isArray(v));}
 function stable(value){if(Array.isArray(value))return JSON.stringify(value.map(v=>JSON.parse(stable(v))));if(value&&typeof value==='object')return JSON.stringify(Object.fromEntries(Object.keys(value).filter(k=>value[k]!==undefined).sort().map(k=>[k,JSON.parse(stable(value[k]))])));return JSON.stringify(value??null);}
 function mergeRecords(local,remote,base={}){const out={},conflicts=[];for(const id of new Set([...Object.keys(local),...Object.keys(remote)])){const l=local[id],r=remote[id],b=base[id],equal=(a,c)=>stable(a)===stable(c);if(!l)out[id]=r;else if(!r||equal(l,r)||equal(r,b))out[id]=l;else if(equal(l,b))out[id]=r;else{const drafts=[...(l.syncAlternatives||[]),...(r.syncAlternatives||[]),{record:{...r,syncAlternatives:undefined},savedAt:r.updatedAt||null}],seen=new Set();out[id]={...l,syncAlternatives:drafts.filter(d=>{const key=stable(d.record);if(seen.has(key)||key===stable({...l,syncAlternatives:undefined}))return false;seen.add(key);return true;})};conflicts.push(id);}}return {records:clone(out),conflicts};}
 function validate(data){if(!data||!safe(data)||data.format!=='probation-study-desk-sync'||data.schemaVersion!==1||!records(data.study)||!records(data.daily)||JSON.stringify(data).length>4000000)throw Error('不是相容的2.5備份檔或超過4MB，未覆寫本機');const alternatives=(r,check)=>r.syncAlternatives===undefined||(Array.isArray(r.syncAlternatives)&&r.syncAlternatives.length<=100&&r.syncAlternatives.every(d=>d&&check(d.record)));const study=r=>r&&typeof r==='object'&&!Array.isArray(r)&&(r.issue===undefined||(typeof r.issue==='string'&&r.issue.length<=100000))&&(r.pointFeedback===undefined||records(r.pointFeedback))&&(r.assessment==null||(typeof r.assessment==='object'&&!Array.isArray(r.assessment)&&(r.assessment.evidence===undefined||Array.isArray(r.assessment.evidence))&&(r.assessment.warnings===undefined||Array.isArray(r.assessment.warnings))));const daily=r=>r&&typeof r.answer==='string'&&r.answer.length<=100000&&typeof r.review==='boolean'&&typeof r.updatedAt==='string'&&(r.questionSnapshot===undefined||typeof r.questionSnapshot==='string');if(!Object.values(data.study).every(r=>study(r)&&alternatives(r,study)))throw Error('考古題紀錄格式不符');if(!Object.values(data.daily).every(r=>daily(r)&&alternatives(r,daily)))throw Error('模擬題紀錄格式不符');return data;}
 function create(study={},daily={}){return validate({format:'probation-study-desk-sync',schemaVersion:1,updatedAt:new Date().toISOString(),study:clone(study),daily:clone(daily)});}
 function merge(local,remote,base={}){validate(local);validate(remote);const study=mergeRecords(local.study,remote.study,base.study),daily=mergeRecords(local.daily,remote.daily,base.daily);return {data:create(study.records,daily.records),conflicts:[...study.conflicts.map(id=>'考古題 '+id),...daily.conflicts.map(id=>'模擬題 '+id)]};}
 function local(){return create(JSON.parse(localStorage.getItem('probation-study-desk-v24')||'{}'),JSON.parse(localStorage.getItem('probation-daily-github:records:v1')||'{}'));}
 function apply(data){validate(data);const before=local(),keys=['probation-study-desk-v24','probation-daily-github:records:v1'],raw=keys.map(k=>localStorage.getItem(k));localStorage.setItem('probation-v25:before-sync',JSON.stringify(before));try{localStorage.setItem(keys[0],JSON.stringify(data.study));localStorage.setItem(keys[1],JSON.stringify(data.daily));window.Practice25?.replaceRecords(data.study);window.Daily25?.replaceRecords(data.daily);}catch(error){keys.forEach((k,i)=>{try{if(raw[i]===null)localStorage.removeItem(k);else localStorage.setItem(k,raw[i]);}catch{}});try{window.Practice25?.replaceRecords(before.study);window.Daily25?.replaceRecords(before.daily);}catch{}throw Error('套用失敗，同步前備份仍保留：'+error.message);}window.dispatchEvent(new Event('backup25:applied'));}
 function contains(expected,actual){const bare=r=>{const copy={...r};delete copy.syncAlternatives;return stable(copy);};return ['study','daily'].every(scope=>Object.entries(expected[scope]).every(([id,record])=>{const remote=actual[scope][id];if(!remote)return false;const stored=[remote,...(remote.syncAlternatives||[]).map(x=>x.record)].map(bare);return [record,...(record.syncAlternatives||[]).map(x=>x.record)].every(r=>stored.includes(bare(r)));}));}
 root.Backup25={clone,safe,records,validate,create,mergeRecords,merge,local,apply,contains};
})(typeof window==='undefined'?globalThis:window);
