(function(){
 'use strict';const app=window.Practice25,$=id=>document.getElementById(id),el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;},button=(text,fn)=>{const b=el('button',text);b.className='btn';b.type='button';b.onclick=fn;return b;};
 const panel=el('section');panel.className='extension25';$('scoreImprovements').parentElement.appendChild(panel);const weak=el('details'),summary=el('summary','補強清單'),list=el('div');weak.append(summary,list);document.querySelector('.app')?.appendChild(weak);if(!weak.parentElement)panel.after(weak);
 function patch(id,data){if(id===app.getQuestion()?.id)app.patch(data);else{const records=app.getRecords();app.replaceRecords({...records,[id]:{...records[id],...data,updatedAt:new Date().toISOString()}});}window.dispatchEvent(new Event('practice25:changed'));}
 function render(){const q=app.getQuestion(),state=app.getState(),a=state.assessment;panel.replaceChildren(el('h3','逐點核對與誤判回饋'));if(!q)return;
  if(window.PENDING_PILOT_RUBRICS[q.id]){$('directionNote').textContent='2.5提供自動參考分數；AI答案綱要尚未完成人工校準，法規時點、合理異說及實質內容請核對。';$('scoreMode').textContent='2.5 · 自動參考分數';$('pilotRuleStatus').textContent='310題自動參考分數 · 仍待人工校準';}
  if(a&&a.answer!==state.issue)panel.appendChild(el('p','以下對應上次答案；答案已變更，請重新判定。'));
  if(!a?.evidence?.length)panel.appendChild(el('p','作答並按系統判定後，逐項呈現辨識線索及回饋欄位。'));
  for(const [i,row] of (a?.evidence||[]).entries()){const key=i+':'+row.label,f=state.pointFeedback?.[key],box=el('div');box.className='point25';box.append(el('strong',row.label+' · '+({'reference-evidence':'找到線索（不等於答對）',evidence:'找到線索',partial:'部分辨識',missing:'未辨識',manual:'需人工核對'}[row.status]||'需核對')),el('p',row.hint||''));if(row.evidence)box.appendChild(el('blockquote',row.evidence));if(f)box.appendChild(el('p','你的覆核：'+f.choice+'；'+(f.note||'無補充')+(f.answerSnapshot!==a?.answer?'（舊稿回饋）':'')));
   const choice=el('select');choice.setAttribute('aria-label',row.label+'回饋');for(const label of ['請選擇回饋','已答到但未辨識','辨識到了但內容不正確','合理異說／其他答案','此點需要補強','此點已補強'])choice.appendChild(el('option',label));const note=el('textarea');note.maxLength=2000;note.placeholder='你的原句、理由或參考來源（最多2000字）';box.append(choice,note,button('保存回饋',()=>{if(!choice.selectedIndex)return;patch(q.id,{pointFeedback:{...(app.getState().pointFeedback||{}),[key]:{choice:choice.value,note:note.value,weakness:choice.selectedIndex===4,resolved:choice.selectedIndex===5,answerSnapshot:a?.answer,updatedAt:new Date().toISOString()}}});render();}));panel.appendChild(box);
  }
  panel.appendChild(el('p','回饋不會自動改分或覆寫全站評分準則；作答、回饋與補強清單保存在目前瀏覽器，可使用匯出備份。'));
  renderWeakness();
 }
 function renderWeakness(){list.replaceChildren();let count=0;for(const q of app.getQuestions()){const state=app.getRecords()[q.id];if(!state)continue;const rows=(state.assessment?.evidence||[]).map((r,i)=>({r,key:i+':'+r.label})).filter(({r,key})=>!state.pointFeedback?.[key]?.resolved&&(state.pointFeedback?.[key]?.weakness||['missing','partial','manual'].includes(r.status)));const flags=Object.entries(state.pointFeedback||{}).filter(([key,f])=>f.weakness&&!f.resolved&&!rows.some(r=>r.key===key));if(!rows.length&&!flags.length&&!state.review)continue;count++;const box=el('details');box.appendChild(el('summary',q.year+'年 · '+q.subject+' · '+q.title));if(state.assessment?.answer!==state.issue)box.appendChild(el('p','依上次判定列示，修改答案後請重新判定。'));for(const {r,key} of rows)box.append(el('p',r.label+'：'+(r.hint||'')),button('標記已補強',()=>{const latest=app.getRecords()[q.id];patch(q.id,{pointFeedback:{...(latest.pointFeedback||{}),[key]:{...latest.pointFeedback?.[key],choice:'此點已補強',resolved:true,updatedAt:new Date().toISOString()}}});render();}));for(const [key,f] of flags)box.appendChild(el('p',key+'：'+f.note));box.appendChild(button('回到這題',()=>app.select(q.id)));list.appendChild(box);}if(!count)list.appendChild(el('p','目前沒有補強項目。完成判定或標記後會列出。'));}
 window.addEventListener('practice25:render',render);window.addEventListener('practice25:changed',render);window.Review25={render,renderWeakness};render();
})();
